### ISSUE TITLE
node_modules/angular2-uuid/index"' has no exported member 'UuidService'

### ISSUE THREAD

**Issue by suparnavg** [wulfsolter/angular2-uuid#12]
I followed the install and use instructions as given in the main github page, and am getting this error. My angular 4 app does not compile.

`node_modules/angular2-uuid/index"' has no exported member 'UuidService'`

Is it required to install a separate angular2-uuid-service module?

Thanks for your help! :)

**Comment by izht** [comment]
I follow the "document" from npm https://www.npmjs.com/package/angular2-uuid and it's work
```
import { UUID } from 'angular2-uuid';
...
let uuid = UUID.UUID();
```

**Comment by jovanymezura** [comment]
thanks for answering @izht
