### ISSUE TITLE
Error: Cannot resolve 'file' or 'directory' ./index.ts

### ISSUE THREAD

**Issue by newmediamonkey** [wulfsolter/angular2-uuid#4]
./~/angular2-uuid/index.js
Cannot find source file 'index.ts': Error: Cannot resolve 'file' or 'directory' ./index.ts in /node_modules/angular2-uuid

**Comment by ForsetiSWE** [comment]
We are also having this issue. Seems that there is some error in the npm package. There is a index.d.ts file in the npm package, is it being renamed when building the npm package because here on git its called (correctly) index.ts? We are running Angular rc1(soon to upgrade to rc5) if that's whats causing the error?

**Comment by wulfsolter** [comment]
You should never be needing to reference the `index.ts` file.

**Comment by Nalha** [comment]
This error pops up for us running angular 2.0.0 and webpack, there is no index.ts in our angular2-uuid folder either.

**Comment by kzRolo** [comment]
Any update with this issue?

**Comment by wulfsolter** [comment]
Clearly not @kzRolo - You are more than welcome to submit a PR.

**Comment by engordon** [comment]
Fix is to open index.js.map and change "sources":["index.ts"] to "sources":["index.d.ts"]
Can someone submit a PR?

**Comment by wulfsolter** [comment]
`/dist/index.js.map`, as with all files in `/dist` should be generated by running `tsc` on /src.

I no longer use this library, and can't test, so am not comfortable blindly modifying generated code. Changes should happen in root and or /src, not in /dist

**Comment by tonefolder** [comment]
> Fix is to open index.js.map and change "sources":["index.ts"] to "sources":["index.d.ts"]
I don't think that is correct.  Can you post some source code that shows how you are importing the library into your project?

The index.d.ts file is a type definitions file that Typescript uses to read and import the module into your project.  Take a look at the [package.json](https://github.com/wulfsolter/angular2-uuid/blob/master/package.json) file.  The "main" property points to the actual JS source (index.js), and the "typings" property points to the type definitions file (index.d.ts).  AFAIK, the source map doesn't really come into play at compile time.
